sonar.projectKey=search-autocomplete-index-builder-worker
sonar.projectName=Search Autocomplete Index Builder Worker
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.rs
sonar.coverage.exclusions=src/main.rs
sonar.rust.lcov.reportPaths=coverage/lcov.info
sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=coverage/clippy.json
sonar.sourceEncoding=UTF-8
